### ISSUE TITLE
too close atoms in STRU generated by ase-neb-abacus

### ISSUE THREAD

**Issue by xdzhu** [QuantumMisaka/ATST-Tools#1]
First of all, thank you for your "ase-neb-abacus" code. I successfully replicated the example of custom structures for Au-diffu-Cu111 using ase-neb-abacus as below. 

![image](https://github.com/QuantumMisaka/ase-neb-abacus/assets/55775434/0d68da96-9386-4239-9c43-f29de7fb3c78)

However, when attempting to perform the NEB calculation for my own structure, I encountered an error midway. It appears that abacus terminated the calculation due to what it perceived as atoms being **too close together within the NEB-generated STRU file**. This issue caused both the abacus calculation and the "run_neb.py" script to terminate with errors.

I would like to inquire about potential solutions for this situation. Is there a way to set a minimum atomic spacing for structures generated by NEB within "ase-neb-abacus"? Alternatively, is there an option to configure abacus to ignore the problematic structure and proceed with the calculation, regenerating the NEB structure if needed?

I have attached the relevant calculation files and error messages for reference. I'm very appreciated it if you can reply.

[issue-neb-too-close.zip](https://github.com/QuantumMisaka/ase-neb-abacus/files/13223925/issue-neb-too-close.zip)

error message of run_neb.py:

> Notice: Dynamic NEB should be efficient in serial calculation
> ----- Running Dynamic NEB -----
> ----- improvedtangent method is being used -----
> ----- Default scale_fmax = 1.0 -----
> Traceback (most recent call last):
>   File "/home/zhuxd/abacus/5.co-work/2.NUS-STO/1.cell/build-model/2L/neb-relaxed/run_neb.py", line 99, in <module>
>     neb.run(optimizer=optimizer, climb=climb, interpolate=interpolate, fmax=0.05)
>   File "/home/zhuxd/Software/abacus/toolkit/ase-neb-abacus-main/abacus_neb.py", line 174, in run
>     opt.run(fmax)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/optimize/optimize.py", line 275, in run
>     return Dynamics.run(self)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/optimize/optimize.py", line 158, in run
>     for converged in Dynamics.irun(self):
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/optimize/optimize.py", line 124, in irun
>     self.atoms.get_forces()
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/mep/neb.py", line 699, in get_forces
>     forces = super().get_forces()
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/mep/neb.py", line 415, in get_forces
>     forces[i - 1] = images[i].get_forces()
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/atoms.py", line 787, in get_forces
>     forces = self._calc.get_forces(self)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/calculators/abc.py", line 30, in get_forces
>     return self.get_property('forces', atoms)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/calculators/calculator.py", line 502, in get_property
>     self.calculate(atoms, [name], system_changes)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/calculators/genericfileio.py", line 142, in calculate
>     self.results = self.template.read_results(self.directory)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/calculators/abacus.py", line 139, in read_results
>     return read_abacus_results(open(path / f'running_{self.cal_name}.log', 'r'), index=-1)[0]
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/utils/__init__.py", line 487, in iofunc
>     obj = func(fd, *args, **kwargs)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/io/abacus.py", line 1776, in read_abacus_results
>     chunks = _get_abacus_chunks(fd, index, non_convergence_ok)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/utils/__init__.py", line 487, in iofunc
>     obj = func(fd, *args, **kwargs)
>   File "/home/zhuxd/Software/anaconda3/envs/icu/lib/python3.10/site-packages/ase/io/abacus.py", line 1742, in _get_abacus_chunks
>     header_pattern.search(contents).group(1))
> AttributeError: 'NoneType' object has no attribute 'group'

error message of abacus in OUT directory:

>                               ABACUS v3.4.0
> 
>                Atomic-orbital Based Ab-initio Computation at UStc                    
> 
>                      Website: http://abacus.ustc.edu.cn/                             
>                Documentation: https://abacus.deepmodeling.com/                       
>                   Repository: https://github.com/abacusmodeling/abacus-develop       
>                               https://github.com/deepmodeling/abacus-develop         
>                       Commit: unknown
> 
>  Wed Nov  1 13:14:02 2023
>  MAKE THE DIR         : OUT.ABACUS/
> 
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> %%%%%% WARNING  WARNING  WARNING  WARNING  WARNING  %%%%%%
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> !!! WARNING: Some atoms are too close!!!
> !!! Please check the nearest-neighbor list in log file.
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> %%%%%% WARNING  WARNING  WARNING  WARNING  WARNING  %%%%%%
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> 
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> %%%%%% WARNING  WARNING  WARNING  WARNING  WARNING  %%%%%%
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> !!! WARNING: Some atoms are too close!!!
> !!! Please check the nearest-neighbor list in log file.
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> %%%%%% WARNING  WARNING  WARNING  WARNING  WARNING  %%%%%%
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> 
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> %%%%%% WARNING  WARNING  WARNING  WARNING  WARNING  %%%%%%
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> !!! WARNING: Some atoms are too close!!!
> !!! Please check the nearest-neighbor list in log file.
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> %%%%%% WARNING  WARNING  WARNING  WARNING  WARNING  %%%%%%
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> 
> If this structure is what you want, you can set 'min_dist_coef'
> as a smaller value (the current value is 0.2) in INPUT file.
>  
>  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>                          NOTICE                           
>  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>  
>  **The structure is unreasonable!**
>  CHECK IN FILE : OUT.ABACUS/warning.log
>  
>  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>                          NOTICE                           
>  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by QuantumMisaka** [comment]
@xdzhu Thanks for your try and issue!

The atoms in your optimized initial and final image structure is not completely correspondent, for example , in line 109 of your STRU file, the coordinate for `init/STRU` is `0.9034 0.1854 0.6441` while in `final/STRU` is `0.7837 0.8885 0.2421`

You can use `vimdiff` to check the coordinate, you can also use `ase -T gui idpp-guess-neb.traj` to view the image-chain guess to see what's wrong. e.g. in your image chain, the image have problem:

<img width="820" alt="f78295a0d8de2a19ced94daaccaa781" src="https://github.com/QuantumMisaka/ase-neb-abacus/assets/43902832/030b8682-5e54-47a7-b6b2-74c8e2f200ef">

The correspondence problem is a very important problem in NEB. `nebplot.pl` in vtst-tools seems to be robust, but for normal NEB, is your job to keep all atom correspondent to each other. 

NOTICE: in your cell. some atoms are so close to the edge of cell. During local optimization process, these atoms may cross lattice edge and to the other size, there coordinate will change rapidly, e.g. from `0.0002` to `0.9998`  . which will also cause problem. A recommend method is to translate all atom to a same direction with a same step, which can be done by ASE or ATOMKIT

**Comment by xdzhu** [comment]
Thank you for the advice. I will try to sort the STRU in correspondent order by using ATOMKIT.

**Comment by QuantumMisaka** [comment]
If you are still using `ase-neb-abacus`, you can switch to v1.0-dev branch to use the pre-released reconstructed code

**Comment by QuantumMisaka** [comment]
May close now
