### ISSUE TITLE
ASE problem: unreasonable init_neb_chain.traj with oxygen vacancy diffusion simulation

### ISSUE THREAD

**Issue by xdzhu** [QuantumMisaka/ATST-Tools#10]
Recently, I've been performing calculations related to oxygen vacancies. My objective was to simulate oxygen atom diffusion on the surface of SrTiO3 (STO) using ASE. Essentially, this process can be viewed as an oxygen atom moving from its initial site to a vacant site.

To model this, I created initial and final states differing by the position of a single oxygen atom and relaxed them independently.

Unfortunately, despite ensuring that the atom lists for both the initial and final states are identical, the init_neb_chain.traj file generated by ASE seems to be incorrect. Could you offer any advice on how to resolve this issue?

I am now attempting to not relax the initial and final STRU structures while keeping the positions of other atoms strictly the same. Awaiting the test results.

[neb_collapse_issue.zip](https://github.com/QuantumMisaka/ATST-Tools/files/13850312/neb_collapse_issue.zip)

![image](https://github.com/QuantumMisaka/ATST-Tools/assets/55775434/f27ec59d-71d4-4f33-8816-806b32d6a4e2)

**Comment by QuantumMisaka** [comment]
You can just move the atoms in cell up along z-direction. 

If some atoms in the edge of cell, they may cross the boundary during relaxation. Also you can fix the atoms in bottom.
