### ISSUE TITLE
Problems with parallel execution of neb_run or autoneb_run

### ISSUE THREAD

**Issue by kleflick** [QuantumMisaka/ATST-Tools#11]
Hi, I tried to run an neb calculation with abacus with the command mpirun -np gpaw -np 5 python neb_run.py but I get the error
**********************************************************

mpirun does not support recursive calls

**********************************************************
[DESKTOP-OULJIUN:05140] Impossible to open the file /tmp/ompi.DESKTOP-OULJIUN.1000/pid.5113/contact.txt in write mode
[DESKTOP-OULJIUN:05140] [[44144,1],0] ORTE_ERROR_LOG: File open failure in file util/hnp_contact.c at line 91

Do you have a guess what goes wrong and how I can run a neb calculation in parallel?

Thank you 
klemens

**Comment by QuantumMisaka** [comment]
Hi @kleflick  Thank you for using ATST-Tools!
Did you install GPAW and ABACUS by using the exactly same MPI environment？ It is recommended to be checked.

**Comment by kleflick** [comment]
hi James,
I think so but how can I check it?

**Comment by QuantumMisaka** [comment]
You can use `gpaw info` to check your gpaw MPI information. 

It is recommended to reinstall GPAW again in ABACUS environments

**Comment by QuantumMisaka** [comment]
@kleflick  Are there any update ?

**Comment by QuantumMisaka** [comment]
@kleflick I'll close this issue, and if there are any problems you can open it up
