### ISSUE TITLE
WARNING: Total thread number on this node mismatches with hardware availability. This may cause poor performance.

### ISSUE THREAD

**Issue by Luc1anoo** [QuantumMisaka/ATST-Tools#14]
I encountered this warning during autoneb calculation with command: mpirun -n 2 gpaw python autoneb_run.py.
I found this warning will always occur when n_images > 1 in every relaxation calculation if one don't use multi nodes. I thought this might be a little bit not user-friendly...
Perhaps it would be more effective to display the warning once at the start of the autoneb execution.
Thanks.

**Comment by QuantumMisaka** [comment]
@Luc1anoo It is an ABACUS warning, you can refer to 

https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_base/parallel_global.cpp#L200

And this PR of ABACUS will remove this warning

https://github.com/deepmodeling/abacus-develop/pull/3943

**Comment by Luc1anoo** [comment]
Thanks a lot ~
