### ISSUE TITLE
How to perform the resumption in the ase-neb-abacus workflow?

### ISSUE THREAD

**Issue by xdzhu** [QuantumMisaka/ATST-Tools#4]
Due to various reasons, interruptions may occur during the ase-neb-abacus calculations. For instance:
1. A specific abacus SCF calculation for one image fails to get converged, resulting in an error that terminates the entire NEB calculation.
2. The computation is constrained by a time limit on the computing nodes, leading to termination once the allotted time is reached or the task is terminated.

Given these two types of interruptions, how may the calculations be resumed?

执行ase-neb-abacus计算会由于多种原因会出现中断，例如：
1、某个image的某次scf计算不收敛退出，导致整个neb计算报错退出；
2、计算节点被限制运行时间，到时间后退出或者任务被杀掉。

请问，在这两种中断的情况下，如何进行续算呢？

**Comment by QuantumMisaka** [comment]
In the newest version of ATST-Tools, just perform neb_post.py to get `neb_latest.traj`, and just use it as init_guess of NEB process, you can just `cp neb_latest.traj init_neb_chain.traj` or make it done (for adding magmom setting) by `neb_make.py`

**Comment by QuantumMisaka** [comment]
continuation method is in README 续算的方法已经更新到README了
