### ISSUE TITLE
parallel problem on SLURM system

### ISSUE THREAD

**Issue by xdzhu** [QuantumMisaka/ATST-Tools#7]
Recently I found that there have been many updates, salute to the developer!
I have been trying to perform NEB calculations using ATST-Tools v1.2.2 on the **SLURM job system**. This is my first attempt at parallel running since my **previous try on the PBS system failed**. When attempting to use 4 nodes (32 cores per node) and invoke GPAW for parallel computing, I found that although 4 directories were successfully created, the abacus program did not start on each node (**no abacus process was found when SSH to each node, and no output in abacus.out**). Then, when submitting with a single node, although it ran successfully, similar errors were reported. May I ask what might be the cause of this, and how can I successfully initiate image parallelization in my case? 
Thank you very much!

最近又看到更新了不少，给肝帝点赞！我使用1.2.2版本尝试在slurm作业系统上使用ATST-Tools进行NEB计算。在我尝试使用4节点（32核/节点）并调用GPAW进行并行计算时，发现可以成功生成4个文件夹，但在每个node上并没有成功跑起来abacus（ssh到每个节点上发现没有abacus进程，abacus.out无任何输出）。然后，使用单节点提交时，虽然成功运行，但也报有类似错误。请问这是什么原因d导致，在我这种情况下如何能够成功开启image并行？非常感谢！

Calculation files: [neb-slurm-4node.zip](https://github.com/QuantumMisaka/ATST-Tools/files/13539066/neb-slurm-4node.zip)

Environment:
intel onepi 2021.3
gnu 11.2.1
ase 3.23b1
gpaw info:
![image](https://github.com/QuantumMisaka/ATST-Tools/assets/55775434/9730043b-b36a-4926-9422-850fd04b1ee0)

4 node running_neb.err:
> srun: Job 9892350 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892350 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892350 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892350 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892350 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892350 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892350 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892350 step creation still disabled, retrying (Requested nodes are busy)

1 node running_neb.err:
> srun: Job 9892355 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation temporarily disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Step created for job 9892355
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Job 9892355 step creation still disabled, retrying (Requested nodes are busy)
> srun: Step created for job 9892355

**Comment by QuantumMisaka** [comment]
I notice that you just use OpenMP to do ABACUS calculation to match the `cpus-per-task` setting, which is no need. You can just set MPI and OpenMP parallel running setting, just make sure that MPI process * OpenMP process = `cpus-per-task` setting.

For this problem, it seems that your abacus is failed to run in your slurm system, I think it is not a problem for ATST-Tools, but a problem for your HPC machine or ASE-ABACUS interfaces when using `mpirun -np 1 abacus`. You can have more try

It is also weird that ATST-Tools will fail in PBS system, but for NEB, related parallel setting and parallel performance in HPC machine is significant surely.

**Comment by xdzhu** [comment]
Thank you! I have modified the submit_neb.sh script as suggested, and now it is capable of executing parallel computations across multiple images. However, in the case of **parallel computing across 4 nodes, I noticed that only 3 nodes are running the abacus process**, while the node assigned to submit_neb.sh has no abacus process running.

**Could you please help me check the input and output files to see why abacus is not successfully running on all 4 nodes? It contains both 32mpi and 8mpi calculations. Thank you very much.**
[neb-4nodes.zip](https://github.com/QuantumMisaka/ATST-Tools/files/13545441/neb-4nodes.zip)

It's worth mentioning that its mode of operation is as follows:
It is from
> NEBrun-rank0  running
> NEBrun-rank1  running
> **NEBrun-rank2  pending**
> NEBrun-rank3  running

goes to
> NEBrun-rank0  done
> NEBrun-rank1  done
> **NEBrun-rank2  running**
> NEBrun-rank3  done

Not always NEBrun-rank2 be pending, it also can be either of them, bu**t the Host node seems to be idle all the time**.

On BatchHost=h03r3n04 :

> ![image](https://github.com/QuantumMisaka/ATST-Tools/assets/55775434/e2b4e6b7-e695-46cc-90ed-36c676fe0e32)

And other 3 nodes h03r3n05~h03r3n07 are like:

> ![image](https://github.com/QuantumMisaka/ATST-Tools/assets/55775434/82f4c27c-cda1-4cfe-8cd6-ef76522c8fe4)




**Additionally, when I set the computation with neb parrallel running abacus on each node (32 cores per node), I always receive warnings like (not get these warning when run ABACUS in standalone job):**

> ![image](https://github.com/QuantumMisaka/ATST-Tools/assets/55775434/cf44277c-33c5-4488-a9f5-0d49be180539)

> ![image](https://github.com/QuantumMisaka/ATST-Tools/assets/55775434/7173f381-9f77-44e8-9581-8c99c4da7afa)



Note: to run abacus, I can use these commands:
nodes=2, mpi=1, omp=32
`mpirun -np 2 -ppn 1 -genv OMP_NUM_THREADS=32 -genv I_MPI_PIN_DOMAIN=omp abacus`

nodes=1, mpi=1, omp=32
`mpirun -np 1 -genv OMP_NUM_THREADS=32 -genv I_MPI_PIN_DOMAIN=omp abacus`

nodes=1, mpi=4, omp=8
`mpirun -np 4 -genv OMP_NUM_THREADS=8 -genv I_MPI_PIN_DOMAIN=omp abacus`

**Comment by QuantumMisaka** [comment]
@xdzhu I think it is still a problem of your slurm service. may you contact your HPC manager and have some discussion? Because everything in my HPC computer is normal now

**Comment by xdzhu** [comment]
Factos, the issue indeed is with the cluster. 

In this system, I should set the number of nodes to 6 for performing an NEB calculation with nmax=5, i.e. `#SBATCH -N `should be `nmax+1`.
